In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [24]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [25]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [26]:
y

array([ 5, 20, 14, 32, 22, 38])

In [40]:
model = LinearRegression().fit(x, y)

In [41]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.7158756137479542


In [42]:
print(f"intercept: {model.intercept_}")

intercept: 5.633333333333329


In [43]:
print(f"slope: {model.coef_}")

slope: [0.54]


In [38]:
#model = LinearRegression()

In [39]:
#model.fit(x, y)

In [44]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [33]:
#new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
#print(f"intercept: {new_model.intercept_}")

In [12]:
#print(f"slope: {new_model.coef_}")

In [37]:
#y_pred = model.predict(x)
#print(f"predicted response:\n{y_pred}")

In [18]:
#y_pred = model.intercept_ + model.coef_ * x
#print(f"predicted response:\n{y_pred}")